---

- name: Install homebrew (using CURL)
  shell: '/usr/bin/ruby -e \
    "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"'

- name: homebrew add tab's
  homebrew_tap: "tap={{ item }} state=present"
  with_items: "{{ brew_taps }}"
  when: brew_taps > 0

- name: homebrew install packages
  homebrew:
    name: "{{ item.name | default(item) }}"
    install_options: "{{ item.install_options | default(omit) }}"
    state: present
    update_homebrew: yes
  with_items: "{{ brew_packages }}"

- name: homebrew cask install packages
  homebrew_cask:
    name: "{{ item.name | default(item) }}"
    install_options: "{{ item.install_options | default(omit) }}"
    state: present
  with_items: "{{ brew_cask_packages }}"
  tags:
    - travis-do-not
