---

- name: Execute OSX hombrew installation for python
  import_tasks: osx-python-install.yaml
  when: ansible_os_family == 'Darwin'

- name: Copy pip config
  copy:
    src: "{{ role_path }}/files/"
    dest: "~"
    force: yes

- name: Upgrade pip
  pip:
    name: pip
    state: latest
  environment:
        PIP_REQUIRE_VIRTUALENV: false

- name: Install system python packages
  pip:
    name: "{{ item }}"
    state: latest
  loop: "{{ python_packages }}"
  environment:
        PIP_REQUIRE_VIRTUALENV: false
