---

- name: Install oh-my-zsh (using git clone)
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh
    dest: ~/.oh-my-zsh

- name: Clone zsh plugin zsh-autosuggestions
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
    dest: ~/.zsh_oh-my-zsh/plugins/zsh-autosuggestions

- name: Clone zsh plugin zsh-syntax-highlighting
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: ~/.zsh_oh-my-zsh/plugins/zsh-syntax-highlighting

- name: Retrive zsh path
  shell: which zsh
  register: zsh_path

- name: Add {{ zsh_path.stdout }} to /etc/shells
  lineinfile:
    path: /etc/shells
    line: "{{ zsh_path.stdout }}"
  become: true
  become_user: root
  become_method: sudo

- name: Change shell for {{ lookup('env','USER') }} to zsh as default
  shell: chsh -s {{ zsh_path.stdout }} {{ lookup('env','USER') }}
  become: true
  become_user: root
  become_method: sudo
  