---

- name: Install oh-my-zsh (using CURL)
  shell: 'sh -c "$(curl -fsSL \
    https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"'

- name: Clone zsh plugin zsh-autosuggestions
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
    dest: ~/.zsh_oh-my-zsh/plugins/zsh-autosuggestions

- name: Clone zsh plugin zsh-syntax-highlighting
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: ~/.zsh_oh-my-zsh/plugins/zsh-syntax-highlighting
