---

- name: homebrew install vim packages
  homebrew:
    name: "{{ item.name | default(item) }}"
    install_options: "{{ item.install_options | default(omit) }}"
    state: present
    update_homebrew: yes
  with_items:
    - vim
