---

- name: Setup system
  hosts: all
  connection: local
  vars_prompt:
    - name: "git_fullname"
      prompt: "Plese enter your git name e.g Goetz Epperlein?"
      default: "Goetz Epperlein"
      private: no
    - name: "git_mail"
      prompt: "Plese enter your git email e.g Some@foo.bar ?"
      private: no

  roles:
    - homebrew
    - zsh_oh-my-zsh
    - dotfiles
    - git
    - vim
    - sublime
    - tmux
    - python
    - osx
    - homebrew_cleanup
