---

- name: homebrew cask install sublime-text packages
  homebrew_cask:
    name: "{{ item.name | default(item) }}"
    install_options: "{{ item.install_options | default(omit) }}"
    state: present
  with_items:
    - sublime-text

- name: Ensure sublime-text settings directories exist
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - ~/Library/Application Support/Sublime Text 3/Installed Packages
    - ~/Library/Application Support/Sublime Text 3/Packages/User
